# Generated by Django 4.2 on 2023-05-23 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 20, 58, 28, 610990, tzinfo=datetime.timezone.utc)),
        ),
    ]
