# Generated by Django 4.2 on 2023-05-05 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_userid_theme_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 20, 36, 54, 372476, tzinfo=datetime.timezone.utc)),
        ),
    ]
