# Generated by Django 4.2 on 2023-05-05 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_theme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 20, 39, 23, 105142, tzinfo=datetime.timezone.utc)),
        ),
    ]
