# Generated by Django 4.2 on 2023-05-11 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_theme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 16, 18, 16, 824221, tzinfo=datetime.timezone.utc)),
        ),
    ]
