# Generated by Django 4.2 on 2023-06-06 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_voteagainst_options_alter_votefor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 17, 11, 9, 886140, tzinfo=datetime.timezone.utc)),
        ),
    ]
