# Generated by Django 4.2 on 2023-05-13 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_theme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 22, 33, 37, 252579, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(),
        ),
    ]
