# Generated by Django 4.2 on 2023-05-20 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_theme_date_alter_theme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 10, 41, 15, 77213, tzinfo=datetime.timezone.utc)),
        ),
    ]
