# Generated by Django 4.2 on 2023-05-20 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_theme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 10, 43, 35, 806676, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
